package msg

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Bucket) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "versioning":
			z.Versioning, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Versioning")
				return
			}
		case "readonly":
			z.Readonly, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Readonly")
				return
			}
		case "compress":
			z.Compress, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Compress")
				return
			}
		case "store_strategy":
			z.StoreStrategy, err = dc.ReadInt8()
			if err != nil {
				err = msgp.WrapError(err, "StoreStrategy")
				return
			}
		case "data_shards":
			z.DataShards, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "DataShards")
				return
			}
		case "parity_shards":
			z.ParityShards, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ParityShards")
				return
			}
		case "version_remains":
			z.VersionRemains, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "VersionRemains")
				return
			}
		case "create_time":
			z.CreateTime, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "policies":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Policies")
				return
			}
			if cap(z.Policies) >= int(zb0002) {
				z.Policies = (z.Policies)[:zb0002]
			} else {
				z.Policies = make([]string, zb0002)
			}
			for za0001 := range z.Policies {
				z.Policies[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Policies", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Bucket) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "versioning"
	err = en.Append(0x8b, 0xaa, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Versioning)
	if err != nil {
		err = msgp.WrapError(err, "Versioning")
		return
	}
	// write "readonly"
	err = en.Append(0xa8, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Readonly)
	if err != nil {
		err = msgp.WrapError(err, "Readonly")
		return
	}
	// write "compress"
	err = en.Append(0xa8, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Compress)
	if err != nil {
		err = msgp.WrapError(err, "Compress")
		return
	}
	// write "store_strategy"
	err = en.Append(0xae, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79)
	if err != nil {
		return
	}
	err = en.WriteInt8(z.StoreStrategy)
	if err != nil {
		err = msgp.WrapError(err, "StoreStrategy")
		return
	}
	// write "data_shards"
	err = en.Append(0xab, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.DataShards)
	if err != nil {
		err = msgp.WrapError(err, "DataShards")
		return
	}
	// write "parity_shards"
	err = en.Append(0xad, 0x70, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ParityShards)
	if err != nil {
		err = msgp.WrapError(err, "ParityShards")
		return
	}
	// write "version_remains"
	err = en.Append(0xaf, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.VersionRemains)
	if err != nil {
		err = msgp.WrapError(err, "VersionRemains")
		return
	}
	// write "create_time"
	err = en.Append(0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CreateTime)
	if err != nil {
		err = msgp.WrapError(err, "CreateTime")
		return
	}
	// write "update_time"
	err = en.Append(0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UpdateTime)
	if err != nil {
		err = msgp.WrapError(err, "UpdateTime")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "policies"
	err = en.Append(0xa8, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Policies)))
	if err != nil {
		err = msgp.WrapError(err, "Policies")
		return
	}
	for za0001 := range z.Policies {
		err = en.WriteString(z.Policies[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Policies", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Bucket) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "versioning"
	o = append(o, 0x8b, 0xaa, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67)
	o = msgp.AppendBool(o, z.Versioning)
	// string "readonly"
	o = append(o, 0xa8, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79)
	o = msgp.AppendBool(o, z.Readonly)
	// string "compress"
	o = append(o, 0xa8, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73)
	o = msgp.AppendBool(o, z.Compress)
	// string "store_strategy"
	o = append(o, 0xae, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79)
	o = msgp.AppendInt8(o, z.StoreStrategy)
	// string "data_shards"
	o = append(o, 0xab, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	o = msgp.AppendInt32(o, z.DataShards)
	// string "parity_shards"
	o = append(o, 0xad, 0x70, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	o = msgp.AppendInt32(o, z.ParityShards)
	// string "version_remains"
	o = append(o, 0xaf, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x73)
	o = msgp.AppendInt32(o, z.VersionRemains)
	// string "create_time"
	o = append(o, 0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.CreateTime)
	// string "update_time"
	o = append(o, 0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.UpdateTime)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "policies"
	o = append(o, 0xa8, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Policies)))
	for za0001 := range z.Policies {
		o = msgp.AppendString(o, z.Policies[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Bucket) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "versioning":
			z.Versioning, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Versioning")
				return
			}
		case "readonly":
			z.Readonly, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Readonly")
				return
			}
		case "compress":
			z.Compress, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Compress")
				return
			}
		case "store_strategy":
			z.StoreStrategy, bts, err = msgp.ReadInt8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StoreStrategy")
				return
			}
		case "data_shards":
			z.DataShards, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DataShards")
				return
			}
		case "parity_shards":
			z.ParityShards, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ParityShards")
				return
			}
		case "version_remains":
			z.VersionRemains, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "VersionRemains")
				return
			}
		case "create_time":
			z.CreateTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "policies":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Policies")
				return
			}
			if cap(z.Policies) >= int(zb0002) {
				z.Policies = (z.Policies)[:zb0002]
			} else {
				z.Policies = make([]string, zb0002)
			}
			for za0001 := range z.Policies {
				z.Policies[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Policies", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Bucket) Msgsize() (s int) {
	s = 1 + 11 + msgp.BoolSize + 9 + msgp.BoolSize + 9 + msgp.BoolSize + 15 + msgp.Int8Size + 12 + msgp.Int32Size + 14 + msgp.Int32Size + 16 + msgp.Int32Size + 12 + msgp.Int64Size + 12 + msgp.Int64Size + 5 + msgp.StringPrefixSize + len(z.Name) + 9 + msgp.ArrayHeaderSize
	for za0001 := range z.Policies {
		s += msgp.StringPrefixSize + len(z.Policies[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Extra) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "total":
			z.Total, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Total")
				return
			}
		case "first_version":
			z.FirstVersion, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "FirstVersion")
				return
			}
		case "last_version":
			z.LastVersion, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "LastVersion")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Extra) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "total"
	err = en.Append(0x83, 0xa5, 0x74, 0x6f, 0x74, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Total)
	if err != nil {
		err = msgp.WrapError(err, "Total")
		return
	}
	// write "first_version"
	err = en.Append(0xad, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.FirstVersion)
	if err != nil {
		err = msgp.WrapError(err, "FirstVersion")
		return
	}
	// write "last_version"
	err = en.Append(0xac, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt(z.LastVersion)
	if err != nil {
		err = msgp.WrapError(err, "LastVersion")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Extra) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "total"
	o = append(o, 0x83, 0xa5, 0x74, 0x6f, 0x74, 0x61, 0x6c)
	o = msgp.AppendInt(o, z.Total)
	// string "first_version"
	o = append(o, 0xad, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt(o, z.FirstVersion)
	// string "last_version"
	o = append(o, 0xac, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt(o, z.LastVersion)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Extra) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "total":
			z.Total, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Total")
				return
			}
		case "first_version":
			z.FirstVersion, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FirstVersion")
				return
			}
		case "last_version":
			z.LastVersion, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastVersion")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Extra) Msgsize() (s int) {
	s = 1 + 6 + msgp.IntSize + 14 + msgp.IntSize + 13 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Metadata) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Extra":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Extra")
					return
				}
				z.Extra = nil
			} else {
				if z.Extra == nil {
					z.Extra = new(Extra)
				}
				var zb0002 uint32
				zb0002, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Extra")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Extra")
						return
					}
					switch msgp.UnsafeString(field) {
					case "total":
						z.Extra.Total, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Extra", "Total")
							return
						}
					case "first_version":
						z.Extra.FirstVersion, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Extra", "FirstVersion")
							return
						}
					case "last_version":
						z.Extra.LastVersion, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Extra", "LastVersion")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Extra")
							return
						}
					}
				}
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "bucket":
			z.Bucket, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Bucket")
				return
			}
		case "create_time":
			z.CreateTime, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Metadata) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Extra"
	err = en.Append(0x85, 0xa5, 0x45, 0x78, 0x74, 0x72, 0x61)
	if err != nil {
		return
	}
	if z.Extra == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 3
		// write "total"
		err = en.Append(0x83, 0xa5, 0x74, 0x6f, 0x74, 0x61, 0x6c)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Extra.Total)
		if err != nil {
			err = msgp.WrapError(err, "Extra", "Total")
			return
		}
		// write "first_version"
		err = en.Append(0xad, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Extra.FirstVersion)
		if err != nil {
			err = msgp.WrapError(err, "Extra", "FirstVersion")
			return
		}
		// write "last_version"
		err = en.Append(0xac, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Extra.LastVersion)
		if err != nil {
			err = msgp.WrapError(err, "Extra", "LastVersion")
			return
		}
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "bucket"
	err = en.Append(0xa6, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Bucket)
	if err != nil {
		err = msgp.WrapError(err, "Bucket")
		return
	}
	// write "create_time"
	err = en.Append(0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CreateTime)
	if err != nil {
		err = msgp.WrapError(err, "CreateTime")
		return
	}
	// write "update_time"
	err = en.Append(0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.UpdateTime)
	if err != nil {
		err = msgp.WrapError(err, "UpdateTime")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Metadata) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Extra"
	o = append(o, 0x85, 0xa5, 0x45, 0x78, 0x74, 0x72, 0x61)
	if z.Extra == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 3
		// string "total"
		o = append(o, 0x83, 0xa5, 0x74, 0x6f, 0x74, 0x61, 0x6c)
		o = msgp.AppendInt(o, z.Extra.Total)
		// string "first_version"
		o = append(o, 0xad, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		o = msgp.AppendInt(o, z.Extra.FirstVersion)
		// string "last_version"
		o = append(o, 0xac, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		o = msgp.AppendInt(o, z.Extra.LastVersion)
	}
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "bucket"
	o = append(o, 0xa6, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74)
	o = msgp.AppendString(o, z.Bucket)
	// string "create_time"
	o = append(o, 0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.CreateTime)
	// string "update_time"
	o = append(o, 0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendInt64(o, z.UpdateTime)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Metadata) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Extra":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Extra = nil
			} else {
				if z.Extra == nil {
					z.Extra = new(Extra)
				}
				var zb0002 uint32
				zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Extra")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Extra")
						return
					}
					switch msgp.UnsafeString(field) {
					case "total":
						z.Extra.Total, bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Extra", "Total")
							return
						}
					case "first_version":
						z.Extra.FirstVersion, bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Extra", "FirstVersion")
							return
						}
					case "last_version":
						z.Extra.LastVersion, bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Extra", "LastVersion")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Extra")
							return
						}
					}
				}
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "bucket":
			z.Bucket, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bucket")
				return
			}
		case "create_time":
			z.CreateTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Metadata) Msgsize() (s int) {
	s = 1 + 6
	if z.Extra == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 6 + msgp.IntSize + 14 + msgp.IntSize + 13 + msgp.IntSize
	}
	s += 5 + msgp.StringPrefixSize + len(z.Name) + 7 + msgp.StringPrefixSize + len(z.Bucket) + 12 + msgp.Int64Size + 12 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Version) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "compress":
			z.Compress, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Compress")
				return
			}
		case "store_strategy":
			z.StoreStrategy, err = dc.ReadInt8()
			if err != nil {
				err = msgp.WrapError(err, "StoreStrategy")
				return
			}
		case "data_shards":
			z.DataShards, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "DataShards")
				return
			}
		case "parity_shards":
			z.ParityShards, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ParityShards")
				return
			}
		case "shard_size":
			z.ShardSize, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ShardSize")
				return
			}
		case "size":
			z.Size, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "ts":
			z.Ts, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Ts")
				return
			}
		case "sequence":
			z.Sequence, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Sequence")
				return
			}
		case "hash":
			z.Hash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "uniqueId":
			z.UniqueId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UniqueId")
				return
			}
		case "locate":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Locate")
				return
			}
			if cap(z.Locate) >= int(zb0002) {
				z.Locate = (z.Locate)[:zb0002]
			} else {
				z.Locate = make([]string, zb0002)
			}
			for za0001 := range z.Locate {
				z.Locate[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Locate", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Version) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "compress"
	err = en.Append(0x8b, 0xa8, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Compress)
	if err != nil {
		err = msgp.WrapError(err, "Compress")
		return
	}
	// write "store_strategy"
	err = en.Append(0xae, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79)
	if err != nil {
		return
	}
	err = en.WriteInt8(z.StoreStrategy)
	if err != nil {
		err = msgp.WrapError(err, "StoreStrategy")
		return
	}
	// write "data_shards"
	err = en.Append(0xab, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.DataShards)
	if err != nil {
		err = msgp.WrapError(err, "DataShards")
		return
	}
	// write "parity_shards"
	err = en.Append(0xad, 0x70, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ParityShards)
	if err != nil {
		err = msgp.WrapError(err, "ParityShards")
		return
	}
	// write "shard_size"
	err = en.Append(0xaa, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.ShardSize)
	if err != nil {
		err = msgp.WrapError(err, "ShardSize")
		return
	}
	// write "size"
	err = en.Append(0xa4, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Size)
	if err != nil {
		err = msgp.WrapError(err, "Size")
		return
	}
	// write "ts"
	err = en.Append(0xa2, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Ts)
	if err != nil {
		err = msgp.WrapError(err, "Ts")
		return
	}
	// write "sequence"
	err = en.Append(0xa8, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Sequence)
	if err != nil {
		err = msgp.WrapError(err, "Sequence")
		return
	}
	// write "hash"
	err = en.Append(0xa4, 0x68, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hash)
	if err != nil {
		err = msgp.WrapError(err, "Hash")
		return
	}
	// write "uniqueId"
	err = en.Append(0xa8, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.UniqueId)
	if err != nil {
		err = msgp.WrapError(err, "UniqueId")
		return
	}
	// write "locate"
	err = en.Append(0xa6, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Locate)))
	if err != nil {
		err = msgp.WrapError(err, "Locate")
		return
	}
	for za0001 := range z.Locate {
		err = en.WriteString(z.Locate[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Locate", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Version) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "compress"
	o = append(o, 0x8b, 0xa8, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73)
	o = msgp.AppendBool(o, z.Compress)
	// string "store_strategy"
	o = append(o, 0xae, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79)
	o = msgp.AppendInt8(o, z.StoreStrategy)
	// string "data_shards"
	o = append(o, 0xab, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	o = msgp.AppendInt32(o, z.DataShards)
	// string "parity_shards"
	o = append(o, 0xad, 0x70, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73)
	o = msgp.AppendInt32(o, z.ParityShards)
	// string "shard_size"
	o = append(o, 0xaa, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt64(o, z.ShardSize)
	// string "size"
	o = append(o, 0xa4, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt64(o, z.Size)
	// string "ts"
	o = append(o, 0xa2, 0x74, 0x73)
	o = msgp.AppendInt64(o, z.Ts)
	// string "sequence"
	o = append(o, 0xa8, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65)
	o = msgp.AppendUint64(o, z.Sequence)
	// string "hash"
	o = append(o, 0xa4, 0x68, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.Hash)
	// string "uniqueId"
	o = append(o, 0xa8, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64)
	o = msgp.AppendString(o, z.UniqueId)
	// string "locate"
	o = append(o, 0xa6, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Locate)))
	for za0001 := range z.Locate {
		o = msgp.AppendString(o, z.Locate[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Version) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "compress":
			z.Compress, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Compress")
				return
			}
		case "store_strategy":
			z.StoreStrategy, bts, err = msgp.ReadInt8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StoreStrategy")
				return
			}
		case "data_shards":
			z.DataShards, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DataShards")
				return
			}
		case "parity_shards":
			z.ParityShards, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ParityShards")
				return
			}
		case "shard_size":
			z.ShardSize, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ShardSize")
				return
			}
		case "size":
			z.Size, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "ts":
			z.Ts, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ts")
				return
			}
		case "sequence":
			z.Sequence, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sequence")
				return
			}
		case "hash":
			z.Hash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "uniqueId":
			z.UniqueId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UniqueId")
				return
			}
		case "locate":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Locate")
				return
			}
			if cap(z.Locate) >= int(zb0002) {
				z.Locate = (z.Locate)[:zb0002]
			} else {
				z.Locate = make([]string, zb0002)
			}
			for za0001 := range z.Locate {
				z.Locate[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Locate", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Version) Msgsize() (s int) {
	s = 1 + 9 + msgp.BoolSize + 15 + msgp.Int8Size + 12 + msgp.Int32Size + 14 + msgp.Int32Size + 11 + msgp.Int64Size + 5 + msgp.Int64Size + 3 + msgp.Int64Size + 9 + msgp.Uint64Size + 5 + msgp.StringPrefixSize + len(z.Hash) + 9 + msgp.StringPrefixSize + len(z.UniqueId) + 7 + msgp.ArrayHeaderSize
	for za0001 := range z.Locate {
		s += msgp.StringPrefixSize + len(z.Locate[za0001])
	}
	return
}
