// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: raft_cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftServerItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RaftServerItem) Reset() {
	*x = RaftServerItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raft_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftServerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftServerItem) ProtoMessage() {}

func (x *RaftServerItem) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftServerItem.ProtoReflect.Descriptor instead.
func (*RaftServerItem) Descriptor() ([]byte, []int) {
	return file_raft_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *RaftServerItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftServerItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BootstrapReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*RaftServerItem `protobuf:"bytes,1,rep,name=Services,proto3" json:"Services,omitempty"`
}

func (x *BootstrapReq) Reset() {
	*x = BootstrapReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raft_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BootstrapReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapReq) ProtoMessage() {}

func (x *BootstrapReq) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapReq.ProtoReflect.Descriptor instead.
func (*BootstrapReq) Descriptor() ([]byte, []int) {
	return file_raft_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapReq) GetServices() []*RaftServerItem {
	if x != nil {
		return x.Services
	}
	return nil
}

type Voter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PrevIndex uint64 `protobuf:"varint,3,opt,name=prevIndex,proto3" json:"prevIndex,omitempty"`
}

func (x *Voter) Reset() {
	*x = Voter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raft_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voter) ProtoMessage() {}

func (x *Voter) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voter.ProtoReflect.Descriptor instead.
func (*Voter) Descriptor() ([]byte, []int) {
	return file_raft_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *Voter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Voter) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Voter) GetPrevIndex() uint64 {
	if x != nil {
		return x.PrevIndex
	}
	return 0
}

type AddVoterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voters []*Voter `protobuf:"bytes,1,rep,name=voters,proto3" json:"voters,omitempty"`
}

func (x *AddVoterReq) Reset() {
	*x = AddVoterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raft_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVoterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVoterReq) ProtoMessage() {}

func (x *AddVoterReq) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVoterReq.ProtoReflect.Descriptor instead.
func (*AddVoterReq) Descriptor() ([]byte, []int) {
	return file_raft_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *AddVoterReq) GetVoters() []*Voter {
	if x != nil {
		return x.Voters
	}
	return nil
}

type JoinLeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterId string `protobuf:"bytes,1,opt,name=masterId,proto3" json:"masterId,omitempty"`
}

func (x *JoinLeaderReq) Reset() {
	*x = JoinLeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raft_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinLeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLeaderReq) ProtoMessage() {}

func (x *JoinLeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLeaderReq.ProtoReflect.Descriptor instead.
func (*JoinLeaderReq) Descriptor() ([]byte, []int) {
	return file_raft_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLeaderReq) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

type RemoveFollowerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowerId string `protobuf:"bytes,1,opt,name=followerId,proto3" json:"followerId,omitempty"`
	PrevIndex  uint64 `protobuf:"varint,2,opt,name=prevIndex,proto3" json:"prevIndex,omitempty"`
}

func (x *RemoveFollowerReq) Reset() {
	*x = RemoveFollowerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_raft_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFollowerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFollowerReq) ProtoMessage() {}

func (x *RemoveFollowerReq) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFollowerReq.ProtoReflect.Descriptor instead.
func (*RemoveFollowerReq) Descriptor() ([]byte, []int) {
	return file_raft_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFollowerReq) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *RemoveFollowerReq) GetPrevIndex() uint64 {
	if x != nil {
		return x.PrevIndex
	}
	return 0
}

var File_raft_cmd_proto protoreflect.FileDescriptor

var file_raft_cmd_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x61, 0x66, 0x74, 0x5f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0e, 0x52, 0x61, 0x66, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x41, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x31, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x66,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x4f, 0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x65,
	0x76, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x33, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x06, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x6f,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x22, 0x2b, 0x0a, 0x0d, 0x4a,
	0x6f, 0x69, 0x6e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x65, 0x76, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x32, 0xaa, 0x03, 0x0a, 0x07,
	0x52, 0x61, 0x66, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x33, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f,
	0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x35, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x05, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_raft_cmd_proto_rawDescOnce sync.Once
	file_raft_cmd_proto_rawDescData = file_raft_cmd_proto_rawDesc
)

func file_raft_cmd_proto_rawDescGZIP() []byte {
	file_raft_cmd_proto_rawDescOnce.Do(func() {
		file_raft_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_raft_cmd_proto_rawDescData)
	})
	return file_raft_cmd_proto_rawDescData
}

var file_raft_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_raft_cmd_proto_goTypes = []interface{}{
	(*RaftServerItem)(nil),    // 0: proto.RaftServerItem
	(*BootstrapReq)(nil),      // 1: proto.BootstrapReq
	(*Voter)(nil),             // 2: proto.Voter
	(*AddVoterReq)(nil),       // 3: proto.AddVoterReq
	(*JoinLeaderReq)(nil),     // 4: proto.JoinLeaderReq
	(*RemoveFollowerReq)(nil), // 5: proto.RemoveFollowerReq
	(*EmptyReq)(nil),          // 6: proto.EmptyReq
	(*Response)(nil),          // 7: proto.Response
}
var file_raft_cmd_proto_depIdxs = []int32{
	0,  // 0: proto.BootstrapReq.Services:type_name -> proto.RaftServerItem
	2,  // 1: proto.AddVoterReq.voters:type_name -> proto.Voter
	1,  // 2: proto.RaftCmd.Bootstrap:input_type -> proto.BootstrapReq
	3,  // 3: proto.RaftCmd.AddVoter:input_type -> proto.AddVoterReq
	4,  // 4: proto.RaftCmd.JoinLeader:input_type -> proto.JoinLeaderReq
	5,  // 5: proto.RaftCmd.RemoveFollower:input_type -> proto.RemoveFollowerReq
	6,  // 6: proto.RaftCmd.AppliedIndex:input_type -> proto.EmptyReq
	6,  // 7: proto.RaftCmd.Peers:input_type -> proto.EmptyReq
	6,  // 8: proto.RaftCmd.Config:input_type -> proto.EmptyReq
	6,  // 9: proto.RaftCmd.LeaveCluster:input_type -> proto.EmptyReq
	7,  // 10: proto.RaftCmd.Bootstrap:output_type -> proto.Response
	7,  // 11: proto.RaftCmd.AddVoter:output_type -> proto.Response
	7,  // 12: proto.RaftCmd.JoinLeader:output_type -> proto.Response
	7,  // 13: proto.RaftCmd.RemoveFollower:output_type -> proto.Response
	7,  // 14: proto.RaftCmd.AppliedIndex:output_type -> proto.Response
	7,  // 15: proto.RaftCmd.Peers:output_type -> proto.Response
	7,  // 16: proto.RaftCmd.Config:output_type -> proto.Response
	7,  // 17: proto.RaftCmd.LeaveCluster:output_type -> proto.Response
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_raft_cmd_proto_init() }
func file_raft_cmd_proto_init() {
	if File_raft_cmd_proto != nil {
		return
	}
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_raft_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftServerItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raft_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BootstrapReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raft_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raft_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVoterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raft_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinLeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_raft_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFollowerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_raft_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_cmd_proto_goTypes,
		DependencyIndexes: file_raft_cmd_proto_depIdxs,
		MessageInfos:      file_raft_cmd_proto_msgTypes,
	}.Build()
	File_raft_cmd_proto = out.File
	file_raft_cmd_proto_rawDesc = nil
	file_raft_cmd_proto_goTypes = nil
	file_raft_cmd_proto_depIdxs = nil
}
