// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CapCard: typeof import('./src/components/CapCard.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    ModalTemplate: typeof import('./src/components/ModalTemplate.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    PopTransition: typeof import('./src/components/PopTransition.vue')['default']
    PriListBox: typeof import('./src/components/PriListBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/SelectBox.vue')['default']
    ServerCard: typeof import('./src/components/ServerCard.vue')['default']
    SlotsCard: typeof import('./src/components/SlotsCard.vue')['default']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    UsageLine: typeof import('./src/components/UsageLine.vue')['default']
  }
}
