package system

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Info) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "DiskInfo":
			err = z.DiskInfo.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "DiskInfo")
				return
			}
		case "MemStatus":
			err = z.MemStatus.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "MemStatus")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Info) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "DiskInfo"
	err = en.Append(0x82, 0xa8, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f)
	if err != nil {
		return
	}
	err = z.DiskInfo.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "DiskInfo")
		return
	}
	// write "MemStatus"
	err = en.Append(0xa9, 0x4d, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = z.MemStatus.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "MemStatus")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Info) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "DiskInfo"
	o = append(o, 0x82, 0xa8, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f)
	o, err = z.DiskInfo.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "DiskInfo")
		return
	}
	// string "MemStatus"
	o = append(o, 0xa9, 0x4d, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73)
	o, err = z.MemStatus.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "MemStatus")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Info) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "DiskInfo":
			bts, err = z.DiskInfo.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiskInfo")
				return
			}
		case "MemStatus":
			bts, err = z.MemStatus.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "MemStatus")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Info) Msgsize() (s int) {
	s = 1 + 9 + z.DiskInfo.Msgsize() + 10 + z.MemStatus.Msgsize()
	return
}
